# Generated by Django 5.2.5 on 2025-09-02 16:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('last_analyzed_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(3, message='Title must be at least 3 characters long')])),
                ('domain', models.CharField(max_length=30)),
                ('target_audience', models.CharField(max_length=30)),
                ('favourited', models.BooleanField(default=False)),
            ],
        ),
    ]
