name: CI Workflow

# Add triggers
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
# Add jobs to execute
jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.9-slim
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
