name: CI Workflow

# Add triggers
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
# Add jobs to execute
jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.13-slim
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python 3.13
        uses: actions/setup-python@v3
        with:
          python-version: "3.13"
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint with flake8
        run: |
          flake8 slidesense --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 slidesense --count --max-complexity=10 --max-line-length=127 --statistics
      - name: Run tests
        run: |
          python manage.py test
